name: Run on runner

on:
  workflow_dispatch

jobs:
  process-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: install deps Download, extract, and build kernel
        run: |
         sudo apt install build-essential gcc-arm-linux-gnueabi gcc-aarch64-linux-gnu  ccache  python-is-python3 libarchive-tools \
         android-sdk-libsparse-utils device-tree-compiler libncurses-dev wget  clang
         curl -LSs "https://raw.githubusercontent.com/JBHPocong/KernelSU-Next/legacy/kernel/setup.sh" | bash -s legacy
         bash run.sh
        
